name: track
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.25=h0dcde21_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py39h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==0.15.0
      - aiohttp==3.7.4.post0
      - aiohttp-cors==0.7.0
      - aioredis==1.3.1
      - armar==1.1.0
      - astunparse==1.6.3
      - async-timeout==3.0.1
      - attrs==25.4.0
      - blessed==1.25.0
      - cachetools==6.2.3
      - certifi==2025.11.12
      - chardet==4.0.0
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - colorful==0.5.8
      - cycler==0.12.1
      - dm-tree==0.1.8
      - filelock==3.19.1
      - flatbuffers==1.12
      - gast==0.4.0
      - google-api-core==2.28.1
      - google-auth==2.43.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - googleapis-common-protos==1.72.0
      - gpustat==1.1.1
      - grpcio==1.34.1
      - gym==0.26.2
      - gym-notices==0.1.0
      - gymnasium==0.26.3
      - gymnasium-notices==0.0.1
      - h5py==3.1.0
      - hiredis==3.3.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2023.7.1
      - keras-nightly==2.5.0.dev2021032900
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.7
      - klimits==1.1.1
      - lz4==4.4.5
      - markdown==3.9
      - markupsafe==3.0.3
      - matplotlib==3.3.4
      - msgpack==1.1.2
      - multidict==6.0.5
      - numpy==1.19.5
      - nvidia-ml-py==13.590.44
      - oauthlib==3.3.1
      - opencensus==0.11.3
      - opencensus-context==0.1.3
      - opencv-python-headless==3.4.18.65
      - opt-einsum==3.3.0
      - packaging==25.0
      - pandas==1.4.4
      - pillow==11.3.0
      - prometheus-client==0.11.0
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==3.20.3
      - psutil==7.1.3
      - py-spy==0.4.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybullet==3.1.7
      - pydantic==1.9.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - ray==1.4.1
      - redis==3.5.3
      - referencing==0.29.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rpds-py==0.27.1
      - rsa==4.9.1
      - scipy==1.5.4
      - six==1.15.0
      - tabulate==0.9.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.4
      - tensorflow-estimator==2.5.0
      - tensorflow-gpu==2.5.0
      - termcolor==1.1.0
      - typing-extensions==3.7.4.3
      - urllib3==2.6.2
      - wcwidth==0.2.14
      - werkzeug==3.1.4
      - wrapt==1.12.1
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/astra/miniconda3/envs/track
